server:
  port: 8080
  servlet:
    context-path: /

#开启或者关闭健康监测功能 日志打印的 Exposing 1 endpoint(s) beneath base path '/actuator'
management:
  endpoint:
    health:
      enabled: false


# 文件基础路径 必填
file-path: D:\webapp\apps\tts
# 日志文件路径 必填
log-file-path: ${file-path}/log
# 日志配置
logging:
  config: classpath:logback-spring.xml
  file:
    path: ${log-file-path}

#微信配置
weixin:
  appId: wx921ec53b18efbfc0
  appSecret: a41127a62fd0f985bb106207f685147d

#netty配置
netty:
  port: 9080
